<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class BooksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('books')->insert([
            [
                'Id' => 'BOOK202112270001',
                'Name' => 'Tư Duy Nhanh Và Chậm',
                'Price' => '40000',
                'Stock' => '30',
                'SaleOff' => null,
                'SaleOffStart' => null,
                'SaleOffEnd' => null,
                'ImgPath' => 'tu-duy-nhanh-va-cham.jpg',
                'Detail' => 'Chúng ta thường tự cho rằng con người là sinh vật có lý trí mạnh mẽ, khi quyết định hay đánh giá vấn đề luôn kĩ lưỡng và lý tính. Nhưng sự thật là, dù bạn có cẩn trọng tới mức nào, thì trong cuộc sống hàng ngày hay trong vấn đề liên quan đến kinh tế, bạn vẫn có những quyết định dựa trên cảm tính chủ quan của mình. Thinking fast and slow, cuốn sách nổi tiếng tổng hợp tất cả nghiên cứu được tiến hành qua nhiều thập kỷ của nhà tâm lý học từng đạt giải Nobel Kinh tế Daniel Kahneman sẽ cho bạn thấy những sư hợp lý và phi lý trong tư duy của chính bạn. Cuốn sách được đánh giá là “kiệt tác” trong việc thay đổi hành vi của con người, Thinking fast and slow đã dành được vô số giải thưởng danh giá, lọt vào Top 11 cuốn sách kinh doanh hấp dẫn nhất năm 2011. Alpha Books đã mua bản quyền và sẽ xuất bản cuốn sách trong Quý 1 năm nay. Thinking fast and slow dù là cuốn sách có tính hàn lâm cao nhưng vô cùng bổ ích với tất cả mọi người và đặc biệt rất dễ hiểu và vui nhộn.Đã có rất nhiều cuốn sách nói về tính hợp lý và phi lý của con người trong tư duy, trong việc đánh giá và ra quyết định, nhưng Thinking fast and slow được Tạp chí Tài chính Mỹ đánh giá là “kiệt tác”.Bạn nghĩ rằng bạn tư duy nhanh, hay chậm? Bạn tư duy và suy nghĩ theo lối “trông mặt bắt hình dong”, đánh giá mọi vật nhanh chóng bằng cảm quan, quyết định dựa theo cảm xúc hay tư duy một cách cẩn thận, chậm rãi nhưng logic hợp lý về một vấn đề. Thinking fast and slow sẽ đưa ra và lý giải hai hệ thống tư duy tác động đến con đường nhận thức của bạn. Kahneman gọi đó là: hệ thống 1 và hệ thống 2. Hệ thống 1, còn gọi là cơ chế nghĩ nhanh, tự động, thường xuyên được sử dụng, cảm tính, rập khuôn và tiềm thức. Hệ thống 2, còn gọi là cơ chế nghĩ chậm, đòi hỏi ít nỗ lực, ít được sử dụng, dùng logic có tính toán và ý thức. Trong một loạt thí nghiệm tâm lý mang tính tiên phong, Kahneman và Tversky chứng minh rằng, con người chúng ta thường đi đến quyết định theo cơ chế nghĩ nhanh hơn là ghĩ chậm. Phần lớn nội dung của cuốn sách chỉ ra những sai lầm của con người khi suy nghĩ theo hệ thống 1. Kahneman chứng minh rằng chúng ta tệ hơn những gì chúng ta tưởng: đó là chúng ta không biết những gì chúng ta không biết!Cuốn sách đặc biệt đã dành được vô số giải thưởng danh giá: Sách khoa học hay nhất của Học viện Khoa học Quốc gia năm 2012, được tạp chí The New York Times bình chọn là sách hay nhất năm 2011, một trong những cuốn sách kinh tế xuất sắc năm 2011, chiến thắng giải thưởng cuốn sách được quan tâm nhất năm 2011 của tạp chí Los Algeles… Thinking fast and slow đáp ứng hai tiêu chí của một cuốn sách hay, thứ nhất nó thách thức quan điểm của người đọc, thứ hai, nó không phải là những trang sách với những con chữ khô cứng mà nó vô cùng vui nhộn và hấp dẫn. Không nghi ngờ gì nữa, đây là cuốn sách hàn lâm dành cho tất cả mọi người.!',
                'Author' => 'Daniel Kahneman',
                'Publisher' => 'NXB Thế giới',
                'CategoryId' => 'TL',
                'Status' => '1',
            ],

            [
                'Id' => 'BOOK202112270002',
                'Name' => 'Đọc Vị Bất Kỳ Ai',
                'Price' => '45000',
                'Stock' => '100',
                'SaleOff' => null,
                'SaleOffStart' => null,
                'SaleOffEnd' => null,
                'ImgPath' => 'doc-vi-bat-ky-ai.jpg',
                'Detail' => 'Bạn băn khoăn không biết người ngồi đối diện đang nghĩ gì? Họ có đang nói dối bạn không? Đối tác đang ngồi đối diện với bạn trên bàn đàm phán đang nghĩ gì và nói gì tiếp theo? ĐỌC người khác là một trong những công cụ quan trọng, có giá trị nhất, giúp ích cho bạn trong mọi khía cạnh của cuộc sống. ĐỌC VỊ người khác để: Hãy chiếm thế thượng phong trong việc chủ động nhận biết điều cần tìm kiếm - ở bất kỳ ai bằng cách “thâm nhập vào suy nghĩ” của người khác. ĐỌC VỊ BẤT KỲ AI là cẩm nang dạy bạn cách thâm nhập vào tâm trí của người khác để biết điều người ta đang nghĩ. Cuốn sách này sẽ không giúp bạn rút ra các kết luận chung về một ai đó dựa vào cảm tính hay sự võ đoán. Những nguyên tắc được chia sẻ trong cuốn sách này không đơn thuần là những lý thuyết hay mẹo vặt chỉ đúng trong một số trường hợp hoặc với những đối tượng nhất định. Các kết quả nghiên cứu trong cuốn sách này được đưa ra dựa trên phương pháp S.N.A.P - cách thức phân tích và tìm hiểu tính cách một cách bài bản trong phạm vi cho phép mà không làm mếch lòng đối tượng được phân tích. Phương pháp này dựa trên những phân tích về tâm lý, chứ không chỉ đơn thuần dựa trên ngôn ngữ cử chỉ, trực giác hay võ đoán. Cuốn sách được chia làm hai phần và 15 chương: Phần 1: Bảy câu hỏi cơ bản: Học cách phát hiện ra điều người khác nghĩ hay cảm nhận một cách dễ dàng và nhanh chóng trong bất kỳ hoàn cảnh nào. Phần 2: Những kế hoạch chi tiết cho hoạt động trí óc - hiểu được quá trình ra quyết định. Vượt ra ngoài việc đọc các suy nghĩ và cảm giác đơn thuần: Hãy học cách người khác suy nghĩ để có thể nắm bắt bất kỳ ai, phán đoán hành xử và hiểu được họ còn hơn chính bản thân họ.',
                'Author' => 'David J. Liebermen',
                'Publisher' => 'ĐH Kinh tế Quốc dân',
                'CategoryId' => 'KNS',
                'Status' => '1',
            ],

            [
                'Id' => 'BOOK202112270003',
                'Name' => 'Cỗ Máy Bán Hàng Tối Ưu',
                'Price' => '35000',
                'Stock' => '60',
                'SaleOff' => null,
                'SaleOffStart' => null,
                'SaleOffEnd' => null,
                'ImgPath' => 'co-may-ban-hang-toi-uu.jpg',
                'Detail' => 'Từng có một câu chuyện về một người bán hàng vĩ đại - người có thể bán bất cứ sản phẩm nào anh ta muốn. Và vì vậy anh ta đã trở thành bậc thầy bán hàng, một tài sản vô giá và là niềm mong ước của mọi doanh nghiệp. Trở thành bậc thầy về bán hàng là niềm mong ước của mọi doanh nghiệp. Điều đó cũng đồng nghĩa với việc tạo lập thành công cho mình một tương lai rộng mở và chắc chắn. Nếu bạn thật sự mong muốn điều đó, cuốn sách Cỗ máy bán hàng tối ưu này sẽ giúp bạn đạt được mục đích của mình. Với một điều kiện: Bạn phải đọc thật kỹ lưỡng, hiểu thật chính xác và làm theo một cách đầy đủ nhất những điều bạn đã đọc được trong cuốn sách này. "Cỗ Máy Bán Hàng Tối Ưu" của Chet Holmes - chuyên gia bán hàng hàng đầu thế giới sẽ mang tới cho bạn những điều thật giản dị như chính cuộc sống của bạn. Mười hai chiến lược bán hàng hiệu quả nhất từ trước đến nay thực chất là 12 công việc mà bất cứ nhân viên bán hàng chuyên nghiệp nào cũng sẽ làm nếu muốn trở thành bậc thầy bán hàng. Lần lượt, từng chiến lược bán hàng được đưa ra như những khớp răng cưa nối kết các phần của cỗ máy bán hàng: Chiến lược 1: Bí quyết quản lý thời gian của các tỷ phú. Chiến lược 2: Xây dựng những tiêu chuẩn cao hơn và tiến hành đào tạo thường kỳ. Chiến lược 3: Tổ chức những buổi hội thảo hiệu quả. Tập trung, kiên định và tính kỷ luật. Thay vì làm 4.000 việc một lúc như trước đây, nay ta chỉ cần làm 12 việc. Thay vì mỗi việc chỉ làm 12 lần, nay ta làm 4.000 lần cho mỗi việc. Đó chính là cách làm cho ta nhanh chóng trở thành chuyên gia bán hàng, giúp ta làm việc khôn ngoan hơn mà không vất vả hơn. Ngoài ra, đây còn là cuốn sách gối đầu giường dành cho nhà quản lý. Ta sẽ tìm thấy đầy đủ cách thức để quản lý hiệu quả quỹ thời gian của mình để thật sự là “nhà quản lý một phút”, ta cũng sẽ biết cách tuyển dụng và giữ chân những nhân viên giỏi, cải thiện chất lượng làm việc của doanh nghiệp, xây dựng được đội ngũ nhân viên bán hàng xuất sắc, cách thức để có trong tay bản danh sách những khách hàng mơ ước…',
                'Author' => 'Chet Holmes',
                'Publisher' => 'NXB Lao động',
                'CategoryId' => 'KD',
                'Status' => '1',
            ],

            [
                'Id' => 'BOOK202112270004',
                'Name' => 'Bí Mật Dotcom',
                'Price' => '27000',
                'Stock' => '43',
                'SaleOff' => null,
                'SaleOffStart' => null,
                'SaleOffEnd' => null,
                'ImgPath' => 'bimat-dotcom-.jpg',
                'Detail' => 'Bí Mật Dotcom đã được GS. Nguyễn Quang Ngọc nhận xét: "Trước hết, nếu bạn đang kỳ vọng Bí Mật Dotcom sẽ đem đến cho bạn những "công cụ" mới mẻ, hấp dẫn, nhanh chóng, dễ dùng hay những mẹo quảng cáo khéo léo, những chiêu trò có thể giúp bạn kiếm tiền ngay hôm nay nhưng đòi hỏi bạn phải liên tục tìm ra những mánh lới khác. Đây không hẳn là điều bạn đang tìm kiếm. Nhưng nếu bạn đang muốn xây dựng một Công Ty Online bền vững, đây đích thị là cuốn sách dành cho bạn. Nó sẽ mang đến cho bạn một sự hiểu biết sâu sắc và một sự thấu suốt về cấu trúc và khoa học marketing hiệu quả để áp dụng chúng trên thế giới truyền thông online. Cuốn sách sẽ giúp bạn biết cách làm thế nào để cấu trúc lại sản phẩm và dịch vụ của công ty mình sao cho số tiền kiếm được nhiều gấp hai đến ba lần từ lượng truy cập bạn đang có. Khi làm theo các bước được hướng dẫn, mọi thứ sẽ bắt đầu vào guồng xoay của nó và bạn có thể đầu tư nhiều hơn để kiếm được nhiều khách hàng mới hơn." Ebook.vn trân trọng giới thiệu với các bạn cuốn bí kíp kiếm tiền "bí mật" này. Hãy đọc, áp dụng nó vào mô hình kinh doanh của bạn, và đừng quên chia sẻ với chúng tôi những thành công và khó khăn của bạn khi áp dụng những bí quyết mà tác giả Russel Brunson mang đến nhé.',
                'Author' => 'Russell Brunson',
                'Publisher' => 'NXB Tổng hợp TP. Hồ Chí Minh',
                'CategoryId' => 'KD',
                'Status' => '1',
            ],

            [
                'Id' => 'BOOK202112270005',
                'Name' => 'Viết Gì Cũng Đúng',
                'Price' => '65000',
                'Stock' => '56',
                'SaleOff' => null,
                'SaleOffStart' => null,
                'SaleOffEnd' => null,
                'ImgPath' => 'viet-gi-cung-dung.jpg',
                'Detail' => 'Cuốn sách này giúp người đọc có một nhận thức đầy đủ và đúng đắn hơn về biện luận, đó không phải chỉ đơn thuần là việc đưa ra những ý kiến của mình dưới một dạng thức mới, mà là việc đưa ra hàng loạt lý do hay bằng chứng để củng cố cho kết luận. Biện luận không phải là tuyên bố hay tranh cãi về một quan điểm hay vấn đề nào đó, mà là cố gắng bảo vệ cho một quan điểm nhất định với các lý lẽ và bằng chứng rõ ràng. Cuốn sách cung cấp cho bạn đọc những kiến thức như: - Những nguyên tắc cơ bản để xử lý các cuộc tranh luận ngắn: xác định giả thuyết và kết luận; phát triển ý tưởng của bạn... - Khái quát hóa: sử dụng nhiều ví dụ; sử dụng các ví dụ điển hình... - Sử dụng phép loại suy từ các ví dụ tương tự; - Các nguồn trích dẫn: tìm kiếm nguồn thông tin; kiểm tra chéo thông tin;... Đôi khi, chúng ta thường coi biện luận là công việc vô ích và chẳng hay ho gì, nhưng chúng ta cũng nhận thức được rằng biện luận là hoàn toàn cần thiết, nhất là trong xã hội ngày nay, con người được trang bị ngày một đầy đủ hơn, toàn diện hơn cả về kiến thức cũng như công cụ để tìm tòi, nghiên cứu, thì biện luận thông minh là cách hữu hiệu để bảo vệ quan điểm cá nhân. Như chính Anthony Weston - tác giả của cuốn sách này đã nói, “Chân lý không bao giờ thay đổi, chỉ có thời gian thay đổi mà thôi.”, và cuốn sách này sẽ giúp bạn đọc làm sáng tỏ nhiều hơn chân lý đó.',
                'Author' => 'Anthony Weston',
                'Publisher' => 'NXB Lao động - Xã hội',
                'CategoryId' => 'KD',
                'Status' => '1',
            ],

            [
                'Id' => 'BOOK202112270006',
                'Name' => 'Tung Sản phẩm',
                'Price' => '73000',
                'Stock' => '75',
                'SaleOff' => null,
                'SaleOffStart' => null,
                'SaleOffEnd' => null,
                'ImgPath' => 'tung-san-pham.jpg',
                'Detail' => 'Dù bạn đã có công việc kinh doanh hay đang nhen nhóm ý định khởi nghiệp thì quyển sách này chính là công thức để giúp bạn có động lực hơn. Hãy nghĩ về điều này – sẽ như thế nào nếu bạn có thể cho ra mắt sản phẩm của bạn như Apple hay những studio lớn của Holywood? Sẽ như thế nào nếu khi mà người tiều dùng của bạn đếm ngược từng ngày để chờ đợi đến khi họ được mua sản phẩm của bạn? Sẽ như thế nào nếu bạn có thể tạo được một chỗ đứng vững chắc trên thị trường mà không đối thủ nào có thể cạnh tranh được với bạn? Và bạn có thể thực hiện được điều đó, dù doanh nghiệp của bạn có quy mô nhỏ hay ngân sách hạn chế.',
                'Author' => 'Jeff Walker',
                'Publisher' => 'NXB Tổng hợp TP. Hồ Chí Minh',
                'CategoryId' => 'KD',
                'Status' => '1',
            ],

            [
                'Id' => 'BOOK202112270007',
                'Name' => 'Cổ Phiếu Thường Lợi Nhuận Phi Thường',
                'Price' => '78000',
                'Stock' => '87',
                'SaleOff' => null,
                'SaleOffStart' => null,
                'SaleOffEnd' => null,
                'ImgPath' => 'co-phieu-thuong-loi-nhuan-phi-thuong.jpg',
                'Detail' => 'Philip Fisher là một trong số các nhà đầu tư có ảnh hưởng lớn nhất mọi thời đại. Triết lý đầu tư của ông không chỉ được nhiều chuyên gia hiện đại nghiên cứu và áp dụng mà còn được rất nhiều nhà đầu tư coi đó là cẩm nang dẫn đường cho bản thân. Những triết lý này đã được tập hợp trong cuốn sách nổi tiếng của ông - Cổ phiếu thường, Lợi nhuận phi thường (Common Stocks and Uncommon Profits), một trong những giáo trình đầu tư kinh điển dành cho các nhà đầu tư hiện đại. Cuốn sách sẽ mang lại cho bạn một cái nhìn toàn diện, từ những vấn đề hết sức cụ thể như sức mạnh của “lời đồn đại”, nên mua gì, khi nào, những điều nhà đầu tư cần tránh, cách tìm ra một cổ phiếu tiềm năng… cho đến phương pháp hình thành một triết lý đầu tư đem lại hiệu quả cao. Fisher đã chỉ ra rằng có hai cách để thu được lợi nhuận đầu tư lớn nhất: thứ nhất là mua cổ phiếu khi thị trường đi xuống và đợi lúc thị trường hồi phục; hoặc áp dụng cách thứ hai ít rủi ro hơn và lợi nhuận tiềm năng lớn hơn, đó là đầu tư vào một số công ty đang tăng trưởng liên tục và thu lợi nhuận hàng năm. Để tìm được chính xác những công ty như vậy, ông cũng đưa ra 15 luận điểm lựa chọn cổ phiếu và những thành tố cần có cho một khoản đầu tư hiệu quả. Có thể nói Cổ phiếu thường, Lợi nhuận phi thường sẽ làm thay đổi cách nhìn nhận của bạn về thị trường tài chính, một cuốn sách xứng đáng có một vị trí trang trọng trên giá sách của các nhà đầu tư và bất cứ ai quan tâm đến lĩnh vực này. Cuốn sách nằm trong “Top 10 cuốn sách về chứng khoán hay nhất mọi thời đại”',
                'Author' => 'Philip A. Fisher',
                'Publisher' => 'Nhà Xuất Bản Lao Động Xã Hội',
                'CategoryId' => 'KD',
                'Status' => '1',
            ],

            [
                'Id' => 'BOOK202112270008',
                'Name' => 'BLOCKCHAIN: Bản chất của Blockchain, Bitcoin, Tiền điện tử',
                'Price' => '37000',
                'Stock' => '80',
                'SaleOff' => null,
                'SaleOffStart' => null,
                'SaleOffEnd' => null,
                'ImgPath' => 'blockchain.jpg',
                'Detail' => 'Tiền điện tử, với đại diện tiêu biểu nhất là Bitcoin, đang là mối quan tâm hàng đầu của giới tài chính toàn cầu. Khả năng thanh toán bằng tiền điện tử mở ra hàng loạt tiềm năng cho thương mại và thay đổi toàn diện thói quen tiêu dùng của con người. Hạt nhân của công nghệ hứa hẹn rung chuyển thế giới này được gọi là Blockchain. Blockchain được giới công nghệ đánh giá là phát kiến vĩ đại nhất sau khi mạng Internet ra đời. Ứng dụng phổ biến nhất của nó là các loại tiền điện tử nổi tiếng (Bitcoin, Ethereum, Ripple...) đang làm mưa làm gió trên thị trường. Nhưng nghịch lý là, lại rất ít người nắm được bản chất của tiền điện tử và Blockchain. Rốt cuộc, Blockchain là gì? Nó hoạt động như thế nào? Blockchain thật sự là một đột phá trong công nghệ hay chỉ là một trào lưu nhất thời? Blockchain có liên hệ như thế nào với Bitcoin? Liệu Blockchain có nắm giữ tiềm năng thay đổi thế giới?... Thực chất, những bài viết cung cấp thông tin về Blockchain và tiền điện tử không thiếu trên các website hay mạng xã hội, nhưng lại chưa đủ tính bao quát và còn khó tiếp thu. Đó là lý do cuốn sách “BLOCKCHAIN: Bản chất của Blockchain, Bitcoin, tiền điện tử, hợp đồng thông minh và tương lai của tiền tệ” của Mark Gates ra đời. Gates cung cấp một bản tóm lược dễ hiểu nhất, cung cấp nền tảng thiết yếu cho những người mới bắt đầu và cả những ai muốn nghiên cứu sâu hơn về công nghệ Blockchain và tiền điện tử. Đọc cuốn sách này, bạn sẽ hiểu được Blockchain dưới nhiều khía cạnh, trong đó không chỉ có những lời ngợi khen mà còn không thiếu các chỉ trích, bình luận trái chiều.',
                'Author' => 'Mark Gates',
                'Publisher' => 'Nhà Xuất Bản Lao Động Xã Hội',
                'CategoryId' => 'KT',
                'Status' => '1',
            ],

            [
                'Id' => 'BOOK202112270009',
                'Name' => 'Bước Ra Khỏi Vùng An Toàn',
                'Price' => '106000',
                'Stock' => '160',
                'SaleOff' => null,
                'SaleOffStart' => null,
                'SaleOffEnd' => null,
                'ImgPath' => 'buoc-ra-khoi-vung-an-toan.jpg',
                'Detail' => '[Bước ra khỏi vùng an toàn - Cuốn sách giúp bạn bứt phá giới hạn bản thân] “Đó là cách tốt nhất để thử thách chính mình. Hãy tận hưởng quá trình và vượt qua giới hạn bản thân” - Richard Branson Bạn đã bao giờ thử dũng cảm làm điều gì đó mà bản thân e sợ? Bạn đã bao giờ thực sự thử thách chính mình, chấp nhận rủi ro để mạnh dạn vượt qua và bứt phá giới hạn bản thân? Nếu câu trả lời của bạn là “chưa” thì rất có thể trong bản thân bạn đang tồn một nỗi sợ vô hình nào đó. Bởi mỗi người trong chúng ta đều có những vùng an toàn khác nhau vì nhiều nguyên nhân khác nhau, nhưng chắc chắn rằng, ai cũng có một vùng an toàn nhất định. Bất kể liên quan đến những nỗi sợ hãi, lo âu tột cùng, những giới hạn ẩn sâu trong tiềm thức hay chỉ là những chứng sợ kỳ quặc, ám ảnh như: Hội chứng sợ độ cao, Hội chứng sợ nha sĩ, Hội chứng sợ nhện,..... Và ắt hẳn, sẽ có nhiều người dành thời gian dài để lên kế hoạch cho một cuộc sống, nhằm không phải tiếp xúc với nỗi sợ, lo âu của bản thân - về căn bản chính là tránh né. Tuy đây được coi là một phương pháp có tác dụng, nhưng không phải là cách giải quyết tối ưu. Vì vậy, thông qua cuốn sách “Bước ra khỏi vùng an toàn", Tiến sĩ tâm lý học - Emma Mardlin sẽ chia sẻ những kiến thức để ta chế ngự mọi nỗi sợ và giới hạn trong thâm tâm bạn, bất kể lớn hay nhỏ. Trong cuốn sách này có rất nhiều mẹo nhanh gọn, kỹ thuật tâm lý và cách tiếp cận mà ngay cả nữ tác giả cũng thường áp dụng để giúp mọi người vượt qua vấn đề, từ những tổn thương sâu sắc đến cả nỗi lo âu dữ dội cản trở họ đạt được những thành công mà bản thân hoàn toàn có thể chinh phục. Có thể nói “Bước ra khỏi vùng an toàn" chính là cuốn cẩm nang toàn diện mà bạn có thể tham khảo bất cứ lúc nào cần đến. Hy vọng bạn đọc có thể bứt phá và sống một cuộc đời không giới hạn! ',
                'Author' => 'Emma Mardlin',
                'Publisher' => 'NXB Thanh Niên',
                'CategoryId' => 'KNS',
                'Status' => '1',
            ],

            [
                'Id' => 'BOOK202112270010',
                'Name' => 'Thế Giới Hậu Vắc Xin Covid 19',
                'Price' => '93000',
                'Stock' => '82',
                'SaleOff' => null,
                'SaleOffStart' => null,
                'SaleOffEnd' => null,
                'ImgPath' => 'the-gioi-hau-covid.jpg',
                'Detail' => 'Sau những dự báo về tương lai và những tác động chưa từng có tiền lệ đối với kinh doanh, nền kinh tế và xã hội của đại dịch Covid-19, trong cuốn sách này, tác giả Jason tiếp tục đưa ra những dự báo về thế giới sau khi vắc xin đã được chủng ngừa rộng rãi. Cuốn sách này sẽ xem xét những thay đổi, thách thức và cơ hội tiềm ẩn mà việc chủng ngừa vắc xin COVID-19 có thể mang lại cho nhiều lĩnh vực và ngành nghề khác nhau như việc làm, giáo dục, y tế, và cả an ninh quốc gia cũng như quan hệ quốc tế. Và theo lời tác giả, tác động của COVID-19 có thể sẽ phủ bóng xuống trong nhiều năm và nhiều thập niên tới đây theo cả chiều hướng tốt và xấu; nó sẽ tác động tới cách chúng ta làm việc, nơi chúng ta sống, và diện mạo của các ngành nghề trong tương lai. Điều quan trọng là chúng ta phải chuẩn bị sẵn sàng cho bất cứ tác động nào của nó, cuốn sách có thể sẽ là “một bộ khung về tương lai để xem xét những tác động tiềm ẩn trước bối cảnh bất ổn cao độ”. “Khủng hoảng này rồi sẽ qua. Chúng ta rồi sẽ hồi phục. Khi đó, muốn thành công, bạn hãy đón nhận các chuyển hóa kỹ thuật số của năm 2020, bao gồm việc chấp nhận rằng một vài biện pháp áp dụng trong ngắn hạn của thời đại dịch có thể sẽ trở thành thường xuyên lâu dài, và một số khác thì không.”',
                'Author' => 'Jason Schenker ',
                'Publisher' => 'NXB Thế Giới',
                'CategoryId' => 'KNS',
                'Status' => '1',
            ],

            [
                'Id' => 'BOOK202112270011',
                'Name' => 'Đắc Nhân Tâm',
                'Price' => '78000',
                'Stock' => '60',
                'SaleOff' => null,
                'SaleOffStart' => null,
                'SaleOffEnd' => null,
                'ImgPath' => 'dac-nhan-tam.jpg',
                'Detail' => 'Nói về đối nhân xử thế',
                'Author' => 'Dale Carnegie',
                'Publisher' => 'Nhà Xuất Bản Tổng hợp TP.HCM',
                'CategoryId' => 'TL',
                'Status' => '1',
            ],

            [
                'Id' => 'BOOK202112270012',
                'Name' => 'Dune Xứ Cát',
                'Price' => '162000',
                'Stock' => '52',
                'SaleOff' => null,
                'SaleOffStart' => null,
                'SaleOffEnd' => null,
                'ImgPath' => 'dune-xu-cat.jpg',
                'Detail' => 'Từ thế hệ này sang thế hệ khác, những nữ phù thủy Bene Gesserit mỏi mòn chờ đợi sự xuất hiện của một B.G. nam giới duy nhất, người có thể vượt qua mọi giới hạn không gian - thời gian…',
                'Author' => 'Frank Herbert',
                'Publisher' => 'Nhà Xuất Bản Hội Nhà Văn',
                'CategoryId' => 'VT',
                'Status' => '1',
            ],

            [
                'Id' => 'BOOK202112270013',
                'Name' => 'đắc nhân tâm',
                'Price' => '780000',
                'Stock' => '30',
                'SaleOff' => null,
                'SaleOffStart' => null,
                'SaleOffEnd' => null,
                'ImgPath' => 'sang-chan-tam-ly-hieu-de-chua-lanh.jpg',
                'Detail' => 'Nói về đối nhân xử thế',
                'Author' => 'Dale Carnegie',
                'Publisher' => 'Nhà Xuất Bản Tổng hợp TP.HCM',
                'CategoryId' => 'TL',
                'Status' => '1',
            ],

            [
                'Id' => 'BOOK202112280014',
                'Name' => 'đắc nhân tâm 9',
                'Price' => '780000',
                'Stock' => '30',
                'SaleOff' => null,
                'SaleOffStart' => null,
                'SaleOffEnd' => null,
                'ImgPath' => 'sang-chan-tam-ly-hieu-de-chua-lanh.jpg',
                'Detail' => 'Nói về đối nhân xử thế',
                'Author' => 'Dale Carnegie',
                'Publisher' => 'Nhà Xuất Bản Tổng hợp TP.HCM',
                'CategoryId' => 'VT',
                'Status' => '1',
            ],

            [
                'Id' => 'BOOK202112290015',
                'Name' => 'Tắt Đèn 2',
                'Price' => '780000',
                'Stock' => '30',
                'SaleOff' => null,
                'SaleOffStart' => null,
                'SaleOffEnd' => null,
                'ImgPath' => '241438765_405068154427447_306993794219947222_n.jpg',
                'Detail' => 'Nói về đối nhân xử thế',
                'Author' => 'Dale Carnegie',
                'Publisher' => 'Nhà Xuất Bản Tổng hợp TP.HCM',
                'CategoryId' => 'TL',
                'Status' => '1',
            ],

            [
                'Id' => 'BOOK202201020016',
                'Name' => 'đắc nhân tâm 89',
                'Price' => '780000',
                'Stock' => '30',
                'SaleOff' => null,
                'SaleOffStart' => null,
                'SaleOffEnd' => null,
                'ImgPath' => 'avatar.jpg',
                'Detail' => 'Nói về đối nhân xử thế',
                'Author' => 'Dale Carnegie',
                'Publisher' => 'Nhà Xuất Bản Tổng hợp TP.HCM',
                'CategoryId' => 'KD',
                'Status' => '1',
            ],

        ]);
    }
}
